test:
#  hostport: httpbin.org:80
#  hostport: localhost:5000
#  uri: http://${test.hostport}
  uri: lb://httpbin

server.port: 8000
jwt.secret: "Ziyouyanfa!@#"
  
---
spring:
  profiles: dev
  profiles.include: routes
  cloud:
    gateway:
      default-filters:
      #- PrefixPath=/httpbin
      #- JwtParser=.*/login
      - AddResponseHeader=Cache-Control, no-cache
      - AddResponseHeader=Pragma, no-cache
      - AddResponseHeader=Expires, -1
mq.host: 192.168.18.100
api.host: 127.0.0.1
        
logging.level.naf.cloud.gateway.*: DEBUG

---
spring:
  profiles: prod
  profiles.include: routes
  cloud:
    gateway:
      default-filters:
      #- PrefixPath=/httpbin
      #- JwtParser=.*/login
      - AddResponseHeader=Cache-Control, no-cache
      - AddResponseHeader=Pragma, no-cache
      - AddResponseHeader=Expires, -1
mq.host: 192.168.1.190       
api.host: 127.0.0.1
        